#pragma once

// ===== Vial =====
#define VIAL_KEYBOARD_UID {0xE6, 0xB5, 0xAD, 0x57, 0x51, 0xA3, 0x3E, 0xF3}
// TAMBAH
#define VIAL_UNLOCK_COMBO_ROWS { 3, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

// ===== Layers =====
#define DYNAMIC_KEYMAP_LAYER_COUNT 7

// ===== RP2040 =====
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
// ===== RGB =====

#define VIAL_RGB_MATRIX_ENABLE

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_RAINDROPS