VIA_ENABLE = yes

VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

# Firmware Optimization
LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes

VIAL_INSECURE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONVERT_TO	= helios